server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
        - id: loan-service
          uri: http://localhost:8082
          predicates:
            - Path=/loan/**